### PR TITLE
Added support for messaging_type - Property Required (Effective May 7, 2018)

### PR DESCRIPTION
**Pull request by mfvitale**
Added support for "messaging_type" according to: https://developers.facebook.com/docs/messenger-platform/send-messages?locale=en_US

Please may you upload on npm the updated version?

### CODE REVIEW

**Comment by ajuhaszcf** [comment]
Can you add an enumeration check not just a generic string?

**Comment by mfvitale** [comment]
Yes. I will do it on Monday.

**Comment by mfvitale** [comment]
May I use "apiCheck.oneOf"  ?

**Comment by mfvitale** [comment]
@adamjuhasz Thank you! May you update it on npm?

**Pull request merged**
